post:
  x-eov-operation-id: deactivateWorkflow
  x-eov-operation-handler: v1/handlers/workflows/workflows.handler
  tags:
  - Workflow
  summary: Deactivate a workflow
  description: Deactivate a workflow.
  parameters:
    - $ref: '../../../../shared/spec/parameters/workflowId.yml'
  responses:
    '200':
      description: Workflow object
      content:
        application/json:
          schema:
            $ref: '../schemas/workflowInformation.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
