---
openapi: 3.0.0
info:
  title: n8n Public API
  description: n8n Public API
  termsOfService: https://n8n.io/legal/terms
  contact:
    email: hello@n8n.io
  license:
    name: Sustainable Use License
    url: https://github.com/n8n-io/n8n/blob/master/packages/cli/LICENSE.md
  version: v1
externalDocs:
  description: n8n API documentation
  url: https://docs.n8n.io/api/
servers:
  - url: /api/v1
tags:
- name: User
  description: Operations about user
- name: Execution
  description: Operations about execution
paths:
  /users:
    post:
      x-eov-operation-id: createUsers
      x-eov-operation-handler: v1/handlers/Users
      tags:
      - User
      summary: Invite a user
      description: Invites a user to your instance. Only available for the instance owner.
      operationId: createUser
      requestBody:
        description: Created user object.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UserInformation'
        required: true
      responses:
        "200":
          description: A User object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInformation'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      x-eov-operation-id: getUsers
      x-eov-operation-handler: v1/handlers/Users
      tags:
      - User
      summary: Retrieve all users
      description: Retrieve all users from your instance. Only available for the instance owner.
      parameters:
      - name: limit
        in: query
        description: The maximum number of items to return.
        required: false
        schema:
          type: number
          example: 100
          default: 100
      - name: cursor
        in: query
        description: Paginate through users by setting the cursor parameter to a nextCursor attribute returned by a previous request's response. Default value fetches the first "page" of the collection. See pagination for more detail.
        required: false
        style: form
        schema:
          type: string
          example: MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA
      - name: includeRole
        in: query
        required: false
        style: form
        description: Whether to include the role information the user object.
        schema:
          type: boolean
          example: false
          default: false
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsResponse'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /users/{identifier}:
    get:
      x-eov-operation-id: getUser
      x-eov-operation-handler: v1/handlers/Users
      tags:
      - User
      summary: Get user by ID/Email
      description: Retrieve a user from your instance. Only available for the instance owner.
      operationId: getUser
      parameters:
      - name: identifier
        in: path
        description: The ID or email of the user.
        required: true
        schema:
          type: string
          format: identifier
      - name: includeRole
        in: query
        required: false
        schema:
          type: boolean
          example: true
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInformation'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      x-eov-operation-id: deleteUser
      x-eov-operation-handler: v1/handlers/Users
      tags:
      - User
      summary: Delete user by ID/Email
      description: Deletes a user from your instance. Only available for the instance owner.
      operationId: deleteUser
      parameters:
      - name: identifier
        in: path
        description: The ID if the user to be deleted.
        required: true
        schema:
          type: string
          format: identifier
      - name: transferId
        in: query
        description: ID of the user to transfer workflows and credentials to. Must not be equal to the to-be-deleted user.
        required: false
        schema:
          type: string
      - name: includeRole
        in: query
        required: false
        schema:
          type: boolean
          example: true
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInformation'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
  /executions:
    get:
      x-eov-operation-id: getExecutions
      x-eov-operation-handler: v1/handlers/Executions
      tags:
      - Execution
      summary: Retrieve all executions
      description: Retrieve all executions from your instance.
      parameters:
      - name: status
        in: query
        description: Status to filter the executions by.
        required: false
        schema:
          type: string
          enum: ['error', 'running', 'success', 'waiting']
          default: 'any'
      - name: workflowId
        in: query
        description: Workflow to filter the executions by.
        required: false
        schema:
          type: number
          example: 1000
      - name: limit
        in: query
        description: The maximum number of items to return.
        required: false
        schema:
          type: number
          example: 100
          default: 100
      - name: cursor
        in: query
        description: Paginate through users by setting the cursor parameter to a nextCursor attribute returned by a previous request's response. Default value fetches the first "page" of the collection. See pagination for more detail.
        required: false
        style: form
        schema:
          type: string
          example: MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionDetailsResponse'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
  /executions/{executionId}:
    get:
      x-eov-operation-id: getExecution
      x-eov-operation-handler: v1/handlers/Executions
      tags:
      - Execution
      summary: Retrieve an execution
      description: Retrieve an execution from you instance.
      parameters:
        - name: executionId
          in: path
          description: The ID of the execution.
          required: true
          schema:
            type: number
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionInformation'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found
    delete:
      x-eov-operation-id: deleteExecution
      x-eov-operation-handler: v1/handlers/Executions
      tags:
      - Execution
      summary: Delete an execution
      description: Deletes an execution from your instance.
      parameters:
      - name: executionId
        in: path
        description: The ID of the execution to be deleted.
        required: true
        schema:
          type: number
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionInformation'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found

components:
  schemas:
    Error:
      required:
      - code
      - description
      - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string
    UserInformation:
      required:
      - email
      type: object
      properties:
        id:
          type: string
          readOnly: true
          example: 123e4567-e89b-12d3-a456-426614174000
        email:
          type: string
          format: email
          example: john.doe@company.com
        firstName:
          maxLength: 32
          type: string
          description: User's first name
          readOnly: true
          example: john
        lastName:
          maxLength: 32
          type: string
          description: User's last name
          readOnly: true
          example: Doe
        isPending:
          type: boolean
          description: Whether the user finished setting up their account in response to the invitation (true) or not (false).
          readOnly: true
        createdAt:
          type: string
          description: Time the user was created.
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          description: Last time the user was updated.
          format: date-time
          readOnly: true
        globalRole:
          $ref: '#/components/schemas/RoleInformation'
    ExecutionDetailsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionInformation'
        nextCursor:
          type: string
          description: Paginate through users by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.
          nullable: true
          example: MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA
    UserDetailsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserInformation'
        nextCursor:
          type: string
          description: Paginate through users by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.
          nullable: true
          example: MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA
    ExecutionInformation:
      type: object
      properties:
        id:
          type: number
          example: 1000
        data:
          type: string
        finished:
          type: boolean
          example: true
        mode:
          type: string
          enum: ['cli', 'error', 'integrated', 'internal', 'manual', 'retry', 'trigger', 'webhook']
        retryOf:
          type: string
          nullable: true
        retrySuccessId:
          type: string
          nullable: true
        startedAt:
          type: string
          format: date-time
        stoppedAt:
          type: string
          format: date-time
        workflowId:
          type: string
          example: 1000
        waitTill:
          type: string
          nullable: true
          format: date-time
    RoleInformation:
      type: object
      properties:
        id:
          type: number
          readOnly: true
          example: 1
        name:
          type: string
          example: owner
          readOnly: true
        scope:
          type: string
          readOnly: true
          example: global
        createdAt:
          type: string
          description: Time the role was created.
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          description: Last time the role was updaded.
          format: date-time
          readOnly: true
  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-N8N-API-KEY

security:
  - ApiKeyAuth: []
