get:
  x-eov-operation-id: getUser
  x-eov-operation-handler: v1/handlers/users/users.handler
  tags:
    - User
  summary: Get user by ID/Email
  description: Retrieve a user from your instance. Only available for the instance owner.
  parameters:
    - $ref: '../schemas/parameters/userIdentifier.yml'
    - $ref: '../schemas/parameters/includeRole.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/user.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
delete:
  x-eov-operation-id: deleteUser
  x-eov-operation-handler: v1/handlers/users/users.handler
  tags:
    - User
  summary: Delete user by ID/Email
  description: Deletes a user from your instance. Only available for the instance owner.
  operationId: deleteUser
  parameters:
    - $ref: '../schemas/parameters/userIdentifier.yml'
    - $ref: '../schemas/parameters/includeRole.yml'
    - name: transferId
      in: query
      description: ID of the user to transfer workflows and credentials to. Must not be equal to the to-be-deleted user.
      schema:
        type: string
        format: identifier
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/user.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
