post:
  x-eov-operation-id: createCredential
  x-eov-operation-handler: v1/handlers/credentials/credentials.handler
  tags:
    - Credential
  summary: Create a credential
  description: Creates a credential that can be used by nodes of the specified type.
  requestBody:
    description: Credential to be created.
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/credential.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/credential.yml'
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '../../../../shared/spec/schemas/error.yml'
    '415':
      description: Unsupported media type.
      content:
        application/json:
          schema:
            $ref: '../../../../shared/spec/schemas/error.yml'
